-- 6-1

-- 1
select LAST_NAME, DEPARTMENT_NAME from EMPLOYEES cross join DEPARTMENTS;

-- 2
select DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID, CITY from DEPARTMENTS natural join LOCATIONS;

-- 3
select DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID, CITY
from DEPARTMENTS natural join LOCATIONS
where DEPARTMENT_ID in (20, 50);


-- 6-2

-- 1
select * from LOCATIONS join DEPARTMENTS D on LOCATIONS.LOCATION_ID = D.LOCATION_ID where D.LOCATION_ID = 1400;

-- 2
select SONG_ID, CD_NUMBER, TITLE, COMMENTS
from D_PLAY_LIST_ITEMS join D_TRACK_LISTINGS using(SONG_ID) join D_CDS using (CD_NUMBER);

-- 3
select CITY, DEPARTMENT_NAME, L.LOCATION_ID, DEPARTMENT_ID
from DEPARTMENTS join LOCATIONS L on L.LOCATION_ID = DEPARTMENTS.LOCATION_ID
where DEPARTMENT_ID in (10, 20, 30) and CITY = 'Seattle';

-- 4
select COUNTRY_NAME, R.REGION_ID, REGION_NAME
from COUNTRIES C join REGIONS R on R.REGION_ID = C.REGION_ID
where REGION_NAME = 'Americas';

-- 5
select FIRST_NAME, LAST_NAME, HIRE_DATE, J.JOB_ID, JOB_TITLE, MAX_SALARY
from EMPLOYEES E join JOBS J on J.JOB_ID = E.JOB_ID
where MIN_SALARY > 12000;

-- 6
select JOB_TITLE, FIRST_NAME, LAST_NAME, EMAIL
from EMPLOYEES E join JOBS J on J.JOB_ID = E.JOB_ID
where JOB_TITLE = 'Stock Clerk';

-- 7
select E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, M.MANAGER_ID, M.FIRST_NAME, M.LAST_NAME
from EMPLOYEES E join EMPLOYEES M on E.MANAGER_ID = M.EMPLOYEE_ID;

-- 8
select L.LOCATION_ID, CITY, DEPARTMENT_NAME
from LOCATIONS L join DEPARTMENTS D on L.LOCATION_ID = D.LOCATION_ID
where COUNTRY_ID = 'CA';

-- 9
select E.MANAGER_ID, DEPARTMENT_NAME, FIRST_NAME, LAST_NAME
from EMPLOYEES E join DEPARTMENTS D on D.DEPARTMENT_ID = E.DEPARTMENT_ID
where D.DEPARTMENT_ID in (80, 90, 110, 190);

-- 10
select EMPLOYEE_ID, LAST_NAME, E.DEPARTMENT_ID, DEPARTMENT_NAME, HIRE_DATE
from EMPLOYEES E join DEPARTMENTS D on D.DEPARTMENT_ID = E.DEPARTMENT_ID
where HIRE_DATE = TO_DATE('1994-06-07', 'YYYY-MM-DD');
