### login
POST http://localhost:1323/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

> {% client.global.set("access_token", response.body.access_token); %}


### get costs
GET http://localhost:1323/api/costs
Accept: application/json
Authorization: Bearer {{access_token}}

### create costs
POST http://localhost:1323/api/costs
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "amount": 1200,
  "source": "Сбербанк",
  "category": "Транспорт",
  "datetime": "2022-12-07T20:30:00"
}

### delete costs
DELETE http://localhost:1323/api/costs/1
Authorization: Bearer {{access_token}}


### get earnings
GET http://localhost:1323/api/earnings
Accept: application/json
Authorization: Bearer {{access_token}}


### create earnings
POST http://localhost:1323/api/earnings
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "amount": 1800,
  "source": "Сбербанк",
  "category": "Перевод",
  "datetime": "2022-12-07T20:30:00"
}

### delete earnings
DELETE http://localhost:1323/api/earnings/1
Authorization: Bearer {{access_token}}
