# 01. Знакомство с `torch.Tensor`

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [611]:
import torch
from torch.nn import functional as f

In [612]:
torch.manual_seed(0);

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [613]:
# 1 операция, но вряд ли от меня этого хотели?

torch.tensor([
    [-4, -3, -2, -6, -5, -2, -3, -4],
    [-1, -1, -1, -1, -1, -1, -1, -1],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [4, 3, 2, 6, 5, 2, 3, 4],
], dtype=torch.float16)

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]], dtype=torch.float16)

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [614]:
even = torch.arange(2, 21, step=2)
even * (even + 1)

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [615]:
# как решить без broadcasting?

torch.arange(1, 8) + torch.arange(0, 101, step=10).reshape(-1, 1)

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [616]:
def textural(n: int, m: int) -> torch.Tensor:
    pat = torch.tensor([
        [0, 1],
        [2, 3]
    ])
    return pat.repeat(((n + 1) // 2, (m + 1 // 2)))[:n, :m]


textural(4, 5)

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [617]:
t: torch.Tensor = torch.empty(4, 7).uniform_(0, 20)  # noqa
t

tensor([[ 9.9251, 15.3644,  1.7695,  2.6406,  6.1485, 12.6816,  9.8019],
        [17.9289,  9.1126, 12.6461,  6.9779,  8.0343,  0.4465,  3.3772],
        [ 5.8778, 10.3704, 13.9534, 16.0002,  3.2206,  5.6454, 13.6322],
        [18.3039,  7.9420, 17.4831,  8.3882, 11.0581, 19.0548,  0.7233]])

In [618]:
min_, max_ = t.min(), t.max()
(t - min_) / (max_ - min_)

tensor([[0.5094, 0.8017, 0.0711, 0.1179, 0.3064, 0.6575, 0.5028],
        [0.9395, 0.4657, 0.6556, 0.3510, 0.4078, 0.0000, 0.1575],
        [0.2919, 0.5333, 0.7259, 0.8359, 0.1491, 0.2794, 0.7086],
        [0.9596, 0.4028, 0.9155, 0.4268, 0.5703, 1.0000, 0.0149]])

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [619]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))

ar1, ar2

(tensor([[9, 0, 1, 2, 3, 0, 5],
         [5, 2, 9, 1, 8, 8, 3],
         [6, 9, 1, 7, 3, 5, 2],
         [1, 0, 9, 3, 1, 1, 0]]),
 tensor([[3, 6, 6, 7, 9, 6, 3],
         [4, 5, 0, 8, 2, 8, 2],
         [7, 5, 0, 0, 8, 1, 9],
         [6, 1, 0, 2, 9, 4, 3]]))

In [620]:
torch.max(ar1, ar2)

tensor([[9, 6, 6, 7, 9, 6, 5],
        [5, 5, 9, 8, 8, 8, 3],
        [7, 9, 1, 7, 8, 5, 9],
        [6, 1, 9, 3, 9, 4, 3]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [621]:
t = torch.randint(low=0, high=100, size=(20,))
i = t.argsort()[-2]
v = t[i]
print(t)
print(f'{v=}, {i=}')

tensor([69, 63,  9, 33, 19, 78, 35, 83, 22, 58, 35, 16, 46, 35, 77, 12,  5, 46,
        56, 15])
v=tensor(78), i=tensor(5)


## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [622]:
torch.arange(1, 8) + torch.arange(0, 101, step=10).reshape(-1, 1)

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [623]:
a_2d = torch.tensor([
    [3, 3, 3],
    [4, 4, 4],
    [5, 5, 5],
])
b_1d = torch.tensor([1, 2, 3])

a_2d - b_1d.reshape(-1, 1)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [624]:
a = torch.tensor([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = torch.tensor([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

(a == b).nonzero(as_tuple=True)[0]  # noqa

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [625]:
torch.arange(9).view(3, 3).flip([0, 1])

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [626]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [627]:
t = torch.arange(9).reshape(3, 3)
t[:, [0, 1]] = t[:, [1, 0]]
t

tensor([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [628]:
t = torch.randint(0, 10, size=(8, 10))
t

tensor([[4, 0, 8, 1, 7, 8, 5, 4, 4, 8],
        [4, 4, 9, 0, 7, 4, 5, 3, 3, 7],
        [3, 0, 9, 9, 3, 1, 8, 1, 7, 8],
        [4, 1, 0, 4, 0, 4, 9, 7, 0, 0],
        [1, 4, 9, 9, 5, 9, 2, 2, 2, 1],
        [4, 9, 1, 1, 0, 3, 0, 6, 7, 6],
        [9, 1, 6, 4, 1, 0, 5, 2, 5, 8],
        [1, 8, 1, 2, 8, 0, 3, 8, 9, 2]])

In [629]:
i = t.sum(1).argmin()
row = t[i]
print(f'{row=}, {i=}')

row=tensor([4, 1, 0, 4, 0, 4, 9, 7, 0, 0]), i=tensor(3)


1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [630]:
t = torch.randint(0, 100, size=(20,))
t

tensor([ 7, 60, 88, 78, 96, 98, 15, 18, 66, 95, 72, 84, 12, 77, 42, 84, 69, 18,
        95,  6])

In [631]:
t.clamp(min=30, max=70)

tensor([30, 60, 70, 70, 70, 70, 30, 30, 66, 70, 70, 70, 30, 70, 42, 70, 69, 30,
        70, 30])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [632]:
a = torch.randint(0, 10, size=(30, 3))
b = torch.randint(0, 10, size=(30, 3))
a, b

(tensor([[4, 3, 3],
         [4, 0, 2],
         [5, 1, 2],
         [8, 2, 4],
         [8, 3, 6],
         [5, 8, 8],
         [0, 5, 1],
         [3, 0, 8],
         [1, 1, 1],
         [7, 2, 2],
         [2, 3, 3],
         [6, 7, 8],
         [0, 5, 0],
         [3, 5, 5],
         [3, 6, 2],
         [2, 5, 5],
         [9, 4, 3],
         [3, 7, 3],
         [8, 0, 7],
         [5, 8, 2],
         [4, 7, 3],
         [2, 5, 5],
         [3, 9, 1],
         [8, 0, 6],
         [7, 4, 7],
         [6, 9, 3],
         [8, 4, 4],
         [9, 4, 4],
         [9, 9, 5],
         [7, 0, 3]]),
 tensor([[2, 0, 8],
         [6, 1, 9],
         [1, 6, 9],
         [8, 6, 5],
         [1, 3, 5],
         [5, 3, 6],
         [2, 7, 5],
         [7, 7, 3],
         [1, 5, 9],
         [5, 9, 6],
         [0, 0, 6],
         [5, 1, 5],
         [0, 1, 7],
         [7, 1, 5],
         [9, 1, 2],
         [0, 0, 6],
         [3, 9, 6],
         [1, 0, 4],
         [5, 6, 9],
         [0, 5, 4]

In [633]:
a[a > b].sum()

tensor(262)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [634]:
t = torch.randint(0, 10, size=(20, 20))
t

tensor([[9, 1, 4, 2, 5, 3, 4, 1, 5, 5, 5, 1, 5, 2, 4, 3, 4, 7, 8, 4],
        [7, 3, 1, 5, 3, 0, 5, 3, 3, 0, 8, 7, 3, 4, 7, 3, 5, 6, 0, 4],
        [9, 8, 2, 0, 0, 6, 8, 9, 1, 9, 2, 6, 9, 9, 7, 4, 1, 8, 5, 8],
        [7, 9, 7, 4, 5, 4, 2, 5, 8, 3, 8, 0, 1, 2, 0, 2, 2, 8, 6, 4],
        [8, 0, 5, 2, 3, 7, 4, 7, 1, 3, 0, 6, 3, 1, 3, 7, 6, 5, 4, 7],
        [2, 0, 2, 6, 1, 5, 5, 7, 5, 4, 7, 6, 3, 8, 1, 4, 7, 3, 6, 2],
        [0, 1, 3, 3, 6, 2, 9, 6, 6, 3, 6, 0, 8, 5, 0, 7, 2, 3, 2, 5],
        [9, 2, 2, 9, 0, 3, 2, 7, 4, 6, 2, 8, 5, 7, 2, 3, 8, 3, 1, 6],
        [7, 0, 0, 4, 4, 6, 3, 1, 6, 8, 4, 4, 5, 7, 8, 0, 7, 4, 1, 7],
        [5, 3, 7, 7, 7, 7, 9, 5, 7, 0, 2, 7, 7, 1, 5, 6, 6, 3, 0, 2],
        [5, 4, 1, 8, 7, 4, 2, 5, 8, 2, 6, 4, 2, 3, 8, 5, 6, 0, 5, 7],
        [1, 3, 8, 4, 7, 2, 3, 5, 1, 9, 0, 0, 1, 4, 6, 3, 5, 9, 0, 0],
        [2, 5, 7, 2, 5, 4, 4, 2, 5, 7, 0, 9, 8, 7, 6, 6, 5, 2, 8, 0],
        [0, 8, 9, 7, 3, 3, 5, 9, 3, 1, 2, 2, 2, 8, 1, 7, 1, 5, 6, 7],
        [4, 0, 9, 5,

In [635]:
t[torch.arange(0, t.shape[0] - 1), torch.arange(1, t.shape[0])]

tensor([1, 1, 0, 5, 7, 5, 6, 4, 8, 2, 4, 1, 7, 1, 4, 3, 8, 0, 1])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [636]:
ar1 = torch.randint(0, 10, size=(5, 10))
ar2 = torch.randint(0, 10, size=(5, 10))

ar1, ar2

(tensor([[2, 9, 6, 0, 1, 6, 6, 4, 7, 3],
         [6, 4, 4, 3, 6, 8, 7, 0, 9, 2],
         [0, 5, 1, 4, 4, 1, 1, 1, 4, 4],
         [6, 6, 0, 5, 8, 4, 8, 2, 0, 7],
         [1, 5, 7, 5, 4, 2, 5, 1, 7, 3]]),
 tensor([[5, 3, 1, 3, 6, 0, 0, 1, 3, 9],
         [7, 0, 0, 3, 6, 5, 3, 5, 5, 1],
         [0, 4, 8, 2, 9, 4, 0, 8, 4, 5],
         [5, 9, 9, 7, 6, 7, 0, 2, 9, 3],
         [9, 3, 1, 2, 0, 5, 6, 2, 3, 1]]))

In [637]:
ar1[ar1 == ar2] *= 2
ar1

tensor([[ 2,  9,  6,  0,  1,  6,  6,  4,  7,  3],
        [ 6,  4,  4,  6, 12,  8,  7,  0,  9,  2],
        [ 0,  5,  1,  4,  4,  1,  1,  1,  8,  4],
        [ 6,  6,  0,  5,  8,  4,  8,  4,  0,  7],
        [ 1,  5,  7,  5,  4,  2,  5,  1,  7,  3]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [638]:
ar1 = torch.randint(0, 10, size=(4, 7))
ar2 = torch.randint(0, 10, size=(4, 7))
ar3 = torch.randint(0, 10, size=(4, 7))

ar1, ar2, ar3

(tensor([[5, 4, 6, 9, 7, 2, 8],
         [0, 5, 9, 4, 7, 8, 7],
         [4, 9, 3, 3, 1, 0, 8],
         [6, 7, 9, 3, 5, 4, 4]]),
 tensor([[2, 4, 4, 6, 9, 3, 4],
         [7, 6, 2, 1, 4, 5, 0],
         [6, 6, 6, 1, 2, 2, 5],
         [3, 0, 6, 9, 4, 7, 2]]),
 tensor([[5, 0, 7, 5, 7, 8, 3],
         [2, 5, 5, 8, 8, 0, 1],
         [1, 0, 4, 6, 6, 4, 6],
         [7, 8, 2, 6, 2, 3, 4]]))

In [639]:
ar1[(ar1 > ar2) & (ar1 < ar3)] = 0
ar1

tensor([[5, 4, 0, 9, 7, 2, 8],
        [0, 5, 9, 0, 0, 8, 7],
        [4, 9, 3, 0, 1, 0, 8],
        [0, 0, 9, 3, 5, 4, 4]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [640]:
ar1 = torch.randint(0, 20, size=(20, 5))
ar1

tensor([[ 0, 12, 17, 13, 12],
        [17, 12, 18,  8,  5],
        [ 6,  4,  8, 13, 17],
        [11,  0, 10,  1, 14],
        [15, 13,  2, 12, 14],
        [ 4,  6,  0,  8, 14],
        [17,  0, 15,  2, 19],
        [16,  4, 10, 19, 12],
        [ 7,  9, 10,  0,  2],
        [ 7,  6,  3, 19,  1],
        [14, 11,  6,  2, 18],
        [18, 16,  3,  6,  4],
        [ 0,  5, 13,  6, 13],
        [ 4,  3, 18,  9,  7],
        [16,  1,  2,  1, 18],
        [ 6, 13,  6,  6, 14],
        [ 3, 14, 17,  2,  6],
        [ 6, 19, 14,  0, 13],
        [ 1,  7, 12,  1,  4],
        [ 1, 19, 13, 11, 11]])

In [641]:
row_max_indices = ar1.argmax(1)
rows, counts = row_max_indices.unique(return_counts=True)
rows[counts >= 5]

tensor([2, 4])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива.

In [642]:
ar1 = torch.rand(4, 7)
ar1, (ar1.max(), ar1.argmax())

(tensor([[0.6960, 0.8688, 0.6200, 0.4506, 0.7479, 0.1826, 0.9891],
         [0.0028, 0.0210, 0.3818, 0.9084, 0.5501, 0.6920, 0.1335],
         [0.6823, 0.4441, 0.7004, 0.8531, 0.7173, 0.4575, 0.4692],
         [0.1864, 0.3191, 0.8249, 0.2995, 0.8105, 0.3017, 0.3836]]),
 (tensor(0.9891), tensor(6)))

In [643]:
i = torch.div(ar1.argmax(), ar1.shape[1], rounding_mode='floor')
j = ar1.argmax() % ar1.shape[1]
ar1[i + 1:, j + 1:] = 0
ar1

tensor([[0.6960, 0.8688, 0.6200, 0.4506, 0.7479, 0.1826, 0.9891],
        [0.0028, 0.0210, 0.3818, 0.9084, 0.5501, 0.6920, 0.1335],
        [0.6823, 0.4441, 0.7004, 0.8531, 0.7173, 0.4575, 0.4692],
        [0.1864, 0.3191, 0.8249, 0.2995, 0.8105, 0.3017, 0.3836]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [651]:
t = torch.tensor([2, 3, 2, 2, 2, 1])
f.one_hot(t - 1)

tensor([[0, 1, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [1, 0, 0]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая.

In [699]:
arr = torch.randint(0, 20, size=(20,))
arr

tensor([ 4, 17,  4,  0, 13, 11,  8,  6, 16,  4,  1,  9, 13, 13,  0, 10, 19, 18,
        10,  9])

In [705]:
values, inverse_indices, counts = arr.unique(sorted=False, return_inverse=True, return_counts=True)
values, inverse_indices, (counts, counts.max(), counts.argmax())

(tensor([ 4, 17, 16,  8,  0, 13, 11,  6,  1,  9, 10, 19, 18]),
 tensor([ 0,  1,  0,  4,  5,  6,  3,  7,  2,  0,  8,  9,  5,  5,  4, 10, 11, 12,
         10,  9]),
 (tensor([3, 1, 1, 1, 2, 3, 1, 1, 1, 2, 2, 1, 1]), tensor(3), tensor(0)))

In [706]:
most_common = values[counts.argmax()]
indices = (arr == most_common).nonzero(as_tuple=True)[0]
print(f'{most_common=}, {indices=}')

most_common=tensor(4), indices=tensor([0, 2, 9])


## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 